version: '3'
services:
    
    proxy:
      container_name: proxy
      build:
        dockerfile: Dockerfile
        context: ./
      ports:
        - '80:80'
      networks:
        - local

    stromy-client-app:
      container_name: stromy-client-app
      build:
        dockerfile: Dockerfile
        context: ../stromy-client-app
      # ports:
      #   - '4041:80'
      networks:
        - local

    stromy-admin-app:
      container_name: stromy-admin-app
      build:
        dockerfile: Dockerfile
        context: ../stromy-admin-app
      # ports:
      #   - '4042:80'
      networks:
        - local

networks:
  local: